# Generated by Django 4.2.1 on 2023-05-09 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GilDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=10000, verbose_name='Контент')),
                ('data_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('completion_date', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Планы развития GILEA',
                'verbose_name_plural': 'Планы развития GILEA',
            },
        ),
        migrations.CreateModel(
            name='Newsroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=10000, verbose_name='Контент')),
                ('category', models.CharField(choices=[('Данные по ценам', 'price_data'), ('Данные по рынку', 'market_data'), ('Данные по производству', 'production data'), ('Данные по торговле', 'trade data'), ('Без категории', 'without category')], default='Без категории', max_length=25, verbose_name='Категория')),
                ('data_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='ComStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('stories', models.TextField(max_length=10000, verbose_name='История')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Истории компаний',
                'verbose_name_plural': 'Истории компаний',
            },
        ),
    ]
