# Generated by Django 4.2.1 on 2023-05-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='category',
            field=models.CharField(choices=[('price_data', 'Данные по ценам'), ('market_data', 'Данные по рынку'), ('production data', 'Данные по производству'), ('trade data', 'Данные по торговле'), ('without cat', 'Без категории')], default='without cat', max_length=25, verbose_name='Категория'),
        ),
    ]
