# Generated by Django 4.2.1 on 2023-05-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0002_alter_newsroom_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='category',
            field=models.CharField(choices=[('price', 'Новости по ценам'), ('market', 'Новости по рынку'), ('production', 'Новости по производству'), ('trade', 'Новости по торговле'), ('without', 'Без категории')], default='without', max_length=25, verbose_name='Категория'),
        ),
    ]
