# Generated by Django 4.2.1 on 2023-05-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0003_alter_newsroom_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gildev',
            name='data_created',
        ),
        migrations.AddField(
            model_name='comstories',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='gildev',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
